#!/usr/bin/env bash
set -e

host_whitelist=($(cat whitelist.txt))
ip_whitelist=()

for host in ${host_whitelist[*]}
do
  if [[ $host =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    ip_whitelist+=($host)
  else
    temp_list=($(dig +short $host))
    for ip in ${temp_list[*]}
    do
      echo "Found $ip for host $host"
      ip_whitelist+=($ip)
    done
  fi
done

for address in ${ip_whitelist[*]}
do
  route add -net $address netmask 255.255.255.255 dev ppp0 || true
done
